
version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: python run.py
        volumes:
            - ./MP220P.:/usr/src/api
        ports:
            - "5000:5000"
        depends_on:
            - db
        env_file:
            - .config
            - .env

    db:
        image: mongo:4.4-bionic
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - volume-db:/var/lib/mongodb/data
        env_file:
            - .config
            - .env

volumes:
    volume-db:
        name: mflix-volume-db
